### ISSUE TITLE
AJT Japanese new menu

### ISSUE THREAD

**Issue by 0xInstrumentarium** [arbyste/jp-mining-note#14]
Minor thing, AJT Japanese changed the way you edit the Add-on, you can't just copy-paste the config, you can still if you click on "View FIles" and open the "config.json". I think it would be useful to mention

**Comment by arbyste** [comment]
To resolve this issue, I released my own version of AJT Japanese which is preconfigured to work with JPMN. 

Make sure to remove or disable the original version of AJT, since the two will probably conflict with each other.

You can find the new version here: https://ankiweb.net/shared/info/200813220
