### ISSUE TITLE
[Feature] Add a sentence translation field

### ISSUE THREAD

**Issue by Thiago-Morais** [arbyste/jp-mining-note#24]
### Your idea

Add a sentence translation field

### Problem to be solved

I have little to no context on the sentence apart from the target term's definition by yomitan
Like grammar and unknown words

<img src="https://github.com/user-attachments/assets/be900724-6250-4439-9b7d-68280454c891" width="50%">

> _Sentence card with no translation for the whole sentence_

### How your idea solves this problem

A sentence translation adds context for the whole sentence, including unknown words, add how the grammar is applied

An intermediary learner can look up each grammar point and add a translation that is more faithful to the target language's structure than standard translation tools, like Google Translate, that tries to make a sentence that sounds natural in the native language

### Workaround

Use `Additional Notes` to add the sentence translation
_This is not ideal since the translation stays hidden, and you have to scroll past the dictionary definition and unfold it to read it_

Or manually add the field on the local card type

### Additional context

I'm a beginner in Japanese and started sentence mining

When I create an Anki sentence card with Yomitan, I have the definition of the target word with yomitan, but I have little to no context for the remainder of the sentence

It would be great to have a field for the sentence translation even if I have to add the translation myself 

I know I could add it on the `Additional Notes` field, but this is not ideal since I have to scroll past the multiple lines dictionary definition and unfold the field

A much better solution would be to have a `SentenceTranslation` field so that I have the sentence translation right below the sentence

As for the argument of "you shouldn't translate the sentence anyway", the idea of a sentence card is to provide the context to which a certain word applies
If I'm a beginner, I don't have enough knowledge to "know every element of a sentence but one"
A sentence translation field provides that context **at a glance**

### Desktop (please complete the following information):

 - OS: Windows 11
 - Anki version: Version ⁨24.11 (87ccd24e)⁩ Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
 - jp-mining-note: v0.12.0.0-prerelease-19

**Comment by arbyste** [comment]
One thing that would make your workaround a bit more convenient is to set your runtime options so that the AdditionalNotes field is automatically opened. See here for details: https://arbyste.github.io/jp-mining-note-prerelease/blockquotes/#automatically-reveal-collapsed-blockquotes

I might consider trying to add a SentenceTranslate field, but there are a few things that I'd like you to consider first:

You point out that an intermediate learner could come up with a reasonable English translation of a sentence, which might be true (depending on the sentence), but you say that you yourself are a beginner. How do you intend to come up with a good translation? Many sources, such as novels and VNs, don't have a straightforward Japanese -> English translation available for each line. For those that do, such as anime with English subs, the translations are very often not a good representation of how to think about the underlying Japanese structure, and are often heavily localized to be more understandable to an English-native audience. I would also strongly advise against using machine translation for this purpose; Google Translate has frequently given me complete rubbish when trying to translate entire sentences. AI might be better, but I haven't used it so I can't really say.

Most guides that recommend sentence cards usually recommend that you start with a beginner vocab deck, such as Kaishi or one of the Core decks, in order to make it easier to find i+1 sentences in your immersion. You could also consider starting off with vocab cards until you're at a point where you can find i+1 sentences easily. Once your sentences truly are i+1, then there's no need for sentence translations, and understanding the sentence itself becomes additional practice. 


The second issue to be aware of is that this will require far more time to create a single card. Out of the box, and with something like ShareX, you can easily create an Anki card with a screenshot in less than 5 seconds. Adding an English translation will likely increase this process to over a minute per card. This fact alone would dissuade me from using this feature. Immersion is far more important than Anki, and it's better to spend 5 seconds making a card, and 55 seconds getting more immersion, vs spending that whole minute making an Anki card.

If you still really want to use English translations, then let me know if the above setting which opens the AdditionalNotes field automatically is sufficient for your needs. If you desperately still want a dedicated sentence translation field, then let me know and I'll consider it, but honestly, I think it will do more harm than good to your Japanese learning.

**Comment by arbyste** [comment]
After considering this further, I don't think I'll add a TranslatedSentence field. Having it there would probably encourage new learners to use it, and for the reasons outlined above that would likely hurt their Japanese progress. Donkuri also raised some additional points to a similar request over on the Lapis notetype: https://github.com/donkuri/lapis/issues/24
